language: node_js
node_js:
  - '0.11'
before_script:
  - npm install -g bower
  - bower install
before_install:
  - 'npm install -g karma-cli'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
